# This is a basic workflow to help you get started with Actions
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # main <-- dev-a
    if: ${{ github.head_ref == 'dev-a' && github.base_ref == 'main' }}
    env:
      PR_NUMBER: $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
         echo ${{ github.ref }}
         echo ${{ github.head_ref }}
         echo ${{ github.base_ref }}
         PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
         echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV
         echo ${{ env.pr_num }}
# echo "::set-output name=pr_num::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
         
        
      - name: Add Comment to Pull Request if Success
        uses: actions/github-script@v5
        with:
          script: |
           await github.rest.issues.createComment({
           owner: context.repo.owner, 
           repo: context.repo.repo, 
           issue_number: ${{ env.pr_num }},
           body: 'It's Success',
           });
